version: "3"
services:
  app:
    container_name: app
    build: ./app

  nginx: 
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    ports:
      - "9000:80"
