version: "3"

networks:
  con_net:
    external: true

services:
  app:
    container_name: app
    build: ./app
    networks:
     - con_net

  nginx: 
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - con_net
    ports:
      - "9000:80"

  nexus:
    image: sonatype/nexus3:latest
    container_name: nexus
    restart: always
    ports:
      - "8081:8081"  # Nexus Web UI
      - "8082:8082"  # Repository API
      - "8083:8083"  # Docker registry
    volumes:
      - nexus-data:/nexus-data
    networks:
      - con_net

volumes:
  nexus-data:
    driver: local
